package de.captaingoldfish.scim.sdk.server.utils;

import lombok.Data;


/**
 * @author Pascal Knueppel
 * @since 14.06.2026
 */
@Data
public class IndexRange
{

  /**
   * the effective startIndex for the request
   */
  private final long startIndex;

  /**
   * the effective count value for the request
   */
  private final int count;

  /**
   * the decoded startIndex from the cursor
   */
  private final long cursorStartIndex;

  /**
   * the unmodified cursor as sent by the client in the request
   */
  private final String cursor;

  /**
   * if the current request is a cursor-request
   */
  private final boolean cursorRequest;

  /**
   * tells us if the encoded cursor was a cursor generated by the SCIM-SDK or if it was generated manually by
   * the developer/client
   */
  private final boolean isInternalCursor;

  public IndexRange(long startIndex, int count, String cursor)
  {
    this.startIndex = startIndex;
    this.count = count;
    long cursorStartIndex = RequestUtils.decodeCursorStartIndex(cursor);
    if (cursorStartIndex == -1)
    {
      this.isInternalCursor = false;
      this.cursorStartIndex = 1;
    }
    else
    {
      this.isInternalCursor = true;
      this.cursorStartIndex = cursorStartIndex;
    }
    this.cursor = cursor;
    this.cursorRequest = cursor != null;
  }

  /**
   * @see #startIndex
   */
  public long getStartIndex()
  {
    return cursorRequest ? cursorStartIndex : startIndex;
  }
}
